### PR TITLE
OpenId apps use TLS (HTTPS) as asked for in challenge #273

### LINKED ISSUE #273: TCK Challenge: openid2 & openid3 need to use TLS endpoint instead of HTTP
**Challenged Tests:**
[ee.jakarta.tck.security.test.OpenId2DefaultIT#testOpenIdConnect](https://github.com/jakartaee/security/blob/master/tck/app-openid2/src/test/java/ee/jakarta/tck/security/test/OpenId2DefaultIT.java#L55)
[ee.jakarta.tck.security.test.OpenId3DefaultIT#testOpenIdConnect](https://github.com/jakartaee/security/blob/master/tck/app-openid3/src/test/java/ee/jakarta/tck/security/test/OpenId3DefaultIT.java#L52)

**TCK Version:**
Jakarta Security TCK 3.0.0

**Tested Implementation:**
Open Liberty

**Description:**
[Section 5.3](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) of the OpenID Connect specification states "Communication with the UserInfo Endpoint MUST utilize TLS," but the OpenId Connect tests in the Security TCK that use Tomcat/Mitre configure it to only have an [HTTP endpoint](https://github.com/jakartaee/security/blob/master/tck/app-openid2/src/main/java/ee/jakarta/tck/security/test/ProtectedServlet.java#L41).

When testing with Open Liberty any attempt to authenticate using the OpenID Connect server is accordingly rejected with the following:
```
io.openliberty.security.oidcclientcore.exceptions.UserInfoEndpointNotHttpsException: CWWKS2418W: The OpenID Connect client
encountered the following error when it sent a request to the [http://localhost:8081/openid-connect-server-webapp/userinfo]
User Info URL of the OpenID Connect provider: CWWKS2402E: The http://localhost:8081/openid-connect-server-webapp/userinfo
endpoint URL that is configured for the {1} OpenID Connect client does not use the HTTPS protocol, but HTTPS is required.
```

The test configuration needs to be updated to use a TLS endpoint so that the scenario meets the requirements of the OpenID Connect specification.

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #273

Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Review by brideck — APPROVED** [review]
These changes work for me and the tests pass, but I see a problem when running them both together.  The keytool plugin will blow up and fail the build in whichever one you run 2nd because it sees that there is already a key with alias 'tomcat' in the trust store.  I don't see a good option off-hand to ignore this kind of failure.

**Comment by arjantijms** [comment]
Hmmm, for some reason that didn't happen here. I've run the full TCK several times.

One option would be to set the homedir of the server being tested to that of the test module. It's currently TCK root/target/glassfish7 for GlassFish.

**Comment by brideck** [comment]
Huh.  Well, I don't think this should be a deal breaker.  Other implementations will have to add/modify in this space anyway since these lines in the pom are Glassfish-specific.

**Comment by teddyjtorres** [comment]
Greetings @arjantijms ,

Please let us know if this PR can be merged and if a 3.0.1 TCK can be released soon. Thanks!

**Comment by arjantijms** [comment]
We should release the 3.0.1 TCK soon indeed

**Pull request merged**
